# raz/config/env/asset.yml
asset:
  engines:
    raz-houdini:
      apps:
        raz-multi-workfiles:
          settings:
            area_template: "@template:asset_work_version_area"
            file_template: "@template:asset_work_version_file"
            version_padding: 3

        raz-multi-publish:
          settings:
            area_template: "@template:asset_publish_version_area"
            file_template: "@template:asset_publish_version_file"
            publish_type: "scene"
            version_padding: 3

    raz-cli:
      apps:
        raz-multi-workfiles:
          settings:
            area_template: "@template:asset_work_version_area"
            file_template: "@template:asset_work_version_file"
            version_padding: 3

        raz-multi-publish:
          settings:
            area_template: "@template:asset_publish_version_area"
            file_template: "@template:asset_publish_version_file"
            publish_type: "scene"
            version_padding: 3
