from __future__ import annotations

from typing import Protocol


class StoragePort(Protocol):
    """Filesystem / remote storage abstraction."""

    def exists(self, path: str) -> bool: ...
    def ensure_dir(self, path: str) -> None: ...
    def write_text(self, path: str, text: str, encoding: str = "utf-8") -> None: ...
    def read_text(self, path: str, encoding: str = "utf-8") -> str: ...